### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Smokyyyyyy** [DIDIRUS4/AstralRinth#3]
### Describe the bug

[11:39:46] [Render thread/INFO]:
 YACL has found 7 images
[11:39:46] [Render thread/INFO]:
 Cached all modded block culling states
[11:39:46] [Worker-Main-1/ERROR]:
 Failed to retrieve profile key pair
com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:100) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.post(MinecraftClient.java:65) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.getKeyPair(YggdrasilUserApiService.java:61) ~[authlib-6.0.52.jar:?]
	at net.minecraft.class_7434.method_43605(class_7434.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_7434.method_44291(class_7434.java:79) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]

**Comment by DIDIRUS4** [comment]
Если вы добавляете пиратскую учетную запись, то эта ошибка будет. Это вызывается методом авторизации с серверами Mojang -> т.е вы не передаете лицензионный токен авторизации в сервис Mojang -> получаете ошибку.
Данной 'ошибки' не будет при использовании лицензии, а также при наличии интернет соединения в этот момент.
